version: "3"
services:
  frontend:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    depends_on:
      - nodeserver
    links:
      - "nodeserver:be"
    volumes:
      - /app/node_modules
      - ./frontend:/app

  nodeserver:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '8081:8081'
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - ./backend:/app

  authserver:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    restart: unless-stopped
    volumes:
      - /app/node_modules
      - ./auth-server:/app

  nginx:
    depends_on:
      - nodeserver
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
